### ISSUE TITLE
testBookAccount not self contained

### ISSUE THREAD

**Issue by mentlsve** [marco-saxer/ownbank#2]
Whether this test succeeds or not depends on the initial account of the balance, can you improve this test to make it self contained.

```
@Test
	public void testBookAccount() throws Exception {
		int amount = 100;
		account.book(amount);
		assertEquals(amount, account.getBalance());

}
```

**Comment by marco-saxer** [comment]
pushed 7717a96d70f464d453eb4c2e1a20f8f87d9c8c40

**Comment by marco-saxer** [comment]
updated new AccountTests
